import type { Season } from "@/lib/game-time";

const icons = {
  rain: [
    ".....b......",
    ".....bb.....",
    "....bbbb....",
    "....bbbb....",
    "...bbbbbb...",
    "..bbbbbbbb..",
    "..bcbbbbbb..",
    ".bbccbbbbbb.",
    ".bbbbbbbbbb.",
    "..bbbbbbbb..",
    "...bbbbbb...",
    "............",
  ],
  leaf: [
    "......g.....",
    ".....lgg....",
    "....lgggg...",
    "...lgggggg..",
    "..lggLggggg.",
    ".lgggLggggg.",
    "..lggLgggg..",
    "...lgLggg...",
    "....gLgg....",
    ".....ww.....",
    "......w.....",
    "............",
  ],
  carrot: [
    "..g....g....",
    ".lg....lg...",
    "..g..Lg.....",
    "...gggg.....",
    "....oo......",
    "...rroor....",
    "...rroor....",
    "..rrroor....",
    "..rorroor...",
    "...rror.....",
    "....or......",
    "....r.......",
  ],
  virus: [
    ".....vv.....",
    "....vmmv....",
    "...vmmmmv...",
    "..vmnfnnmv..",
    "vvmkknnkknvv",
    "vvmkknnkknvv",
    ".vmnnkknnmv.",
    ".vmnnnnnnmv.",
    "..vmnnnnmv..",
    "...vmmmmv...",
    "....vmmv....",
    ".....vv.....",
  ],
  fire: [
    ".....r......",
    ".....rr.....",
    "....rrr.....",
    "....rrro....",
    "..r.rror....",
    "..rrroorr...",
    ".rrroooorr..",
    ".rrooyoorr..",
    "rrrooyyoorr.",
    ".rroyyyorr..",
    "..royyorr...",
    "...oooo.....",
  ],
  tornado: [
    "...ssssss...",
    ".ssssssssss.",
    "sss......sss",
    ".ssssssssss.",
    "...ssssss...",
    "..sssssss...",
    "...ssssss...",
    "....ssss....",
    "....sss.....",
    ".....ss.....",
    ".....s......",
    "............",
  ],
  quake: [
    ".....w......",
    "....www.....",
    "...wwwww....",
    "..wwwwwww...",
    "..wwwwwww...",
    ".wwwww.www..",
    ".wwww.wwwww.",
    "wwwww.wwwwww",
    "wwww...wwwww",
    ".ww.....www.",
    "............",
    "............",
  ],
  lightning: [
    ".....yyyy...",
    "....yyyy....",
    "....yyy.....",
    "...yyy......",
    "...yyyyyyy..",
    "..yyyyyyy...",
    "......yy....",
    ".....yy.....",
    "....yy......",
    "...yy.......",
    "...y........",
    "............",
  ],
  meteor: [
    "..........rr",
    "........rrr.",
    "......rrror.",
    "....rrroor..",
    "...rrooorr..",
    "..ooooorr...",
    ".ooyyyoor...",
    "ooy...yoo...",
    "oy.....yo...",
    "ooy...yoo...",
    ".ooyyyoo....",
    "..ooooo.....",
  ],
  sun: [
    ".....yy.....",
    ".y...yy...y.",
    "..y......y..",
    "....yyyy....",
    "...yyyyyy...",
    "yy.yyyyyy.yy",
    "yy.yyyyyy.yy",
    "...yyyyyy...",
    "....yyyy....",
    "..y......y..",
    ".y...yy...y.",
    ".....yy.....",
  ],
  sunSpring: [
    ".....pp.....",
    ".p...pp...p.",
    "..p......p..",
    "....ppyy....",
    "...ppyyyy...",
    "pp.pyyyyy.pp",
    "pp.pyyyyy.pp",
    "...ppyyyy...",
    "....ppyy....",
    "..p......p..",
    ".p...pp...p.",
    ".....pp.....",
  ],
  sunAutumn: [
    ".....or.....",
    ".s...oo...s.",
    "..s......s..",
    "....oooo....",
    "...orrooo...",
    "oo.orrrro.oo",
    "oo.orrrro.oo",
    "...orrooo...",
    "....oooo....",
    "..s......s..",
    ".s...oo...s.",
    ".....or.....",
  ],
  sunWinter: [
    "....ksk.....",
    ".k...ii...k.",
    "..k......k..",
    "....iddd....",
    "...iddddi...",
    "dd.idddid.dd",
    "dd.idddid.dd",
    "...iddddi...",
    "....iddd....",
    "..k......k..",
    ".k...ii...k.",
    "....ksk.....",
  ],
  heart: [
    "............",
    "..rr..rr....",
    ".rrrrrrrrr..",
    ".rrrrrrrrr..",
    ".rrrrrrrrr..",
    "..rrrrrrr...",
    "...rrrrr....",
    "....rrr.....",
    ".....r......",
    "............",
    "............",
    "............",
  ],
  bulletin: [
    "............",
    ".rrrrrrrrrr.",
    ".r........r.",
    ".r.rrrrrr.r.",
    ".r........r.",
    ".r.rrrrrr.r.",
    ".r........r.",
    ".r.rrrrrr.r.",
    ".r........r.",
    ".rrrrrrrrrr.",
    "............",
    "............",
  ],
  help: [
    "............",
    "..ffffff....",
    ".ff....ff...",
    ".ff....ff...",
    ".......ff...",
    "......ff....",
    ".....ff.....",
    ".....ff.....",
    "............",
    ".....ff.....",
    ".....ff.....",
    "............",
  ],
  speaker: [
    "............",
    ".....ff.....",
    "....fff.f...",
    ".ffffff..f..",
    ".ffffff...f.",
    ".ffffff...f.",
    ".ffffff...f.",
    ".ffffff...f.",
    ".ffffff..f..",
    "....fff.f...",
    ".....ff.....",
    "............",
  ],
  muted: [
    "...........f",
    ".....ff...f.",
    "....fff..f..",
    ".ffffff.f...",
    ".ffffff.....",
    ".fffff......",
    ".ffffff.f...",
    ".ffffff..f..",
    "....fff...f.",
    ".....ff...f.",
    "...........f",
    "............",
  ],
  pause: [
    "............",
    "..fff.fff...",
    "..fff.fff...",
    "..fff.fff...",
    "..fff.fff...",
    "..fff.fff...",
    "..fff.fff...",
    "..fff.fff...",
    "..fff.fff...",
    "..fff.fff...",
    "............",
    "............",
  ],
  play: [
    "............",
    "...f........",
    "...ff.......",
    "...fff......",
    "...ffff.....",
    "...fffff....",
    "...ffffff...",
    "...fffff....",
    "...ffff.....",
    "...fff......",
    "...ff.......",
    "...f........",
  ],
  skip: [
    "............",
    "..f.....ff..",
    "..ff....ff..",
    "..fff...ff..",
    "..ffff..ff..",
    "..fffff.ff..",
    "..fffff.ff..",
    "..ffff..ff..",
    "..fff...ff..",
    "..ff....ff..",
    "..f.....ff..",
    "............",
  ],
  fast: [
    "............",
    ".f....f.....",
    ".ff...ff....",
    ".fff..fff...",
    ".ffff.ffff..",
    ".ffffffffff.",
    ".ffffffffff.",
    ".ffff.ffff..",
    ".fff..fff...",
    ".ff...ff....",
    ".f....f.....",
    "............",
  ],
} as const;

const palette: Record<string, string> = {
  b: "#00a9ee",
  c: "#86e0ff",
  w: "#a57a4c",
  r: "#e54320",
  o: "#ff941b",
  y: "#ffe128",
  p: "#fff6b8",
  i: "#c4d4e0",
  d: "#8a96a4",
  s: "#b8bfc1",
  f: "#f7f2e5",
  k: "#3a4248",
  v: "#d4ff4a",
  n: "#5cbf2e",
  m: "#2d7a16",
  g: "#4ea234",
  l: "#8ed45c",
  L: "#2d6e28",
};

export type IconName = keyof typeof icons;

const SEASON_SUN: Record<
  Season,
  "sun" | "sunSpring" | "sunAutumn" | "sunWinter"
> = {
  Summer: "sun",
  Spring: "sunSpring",
  Autumn: "sunAutumn",
  Winter: "sunWinter",
};

export function seasonSunIcon(season: Season): IconName {
  return SEASON_SUN[season];
}

export function PixelIcon({ name }: { name: IconName }) {
  const pixels = icons[name].flatMap((row, y) =>
    [...row].flatMap((color, x) =>
      color === "." ? [] : [{ id: `${x}-${y}`, x, y, color }],
    ),
  );
  return (
    <svg
      className="pixel-icon"
      viewBox="0 0 12 12"
      aria-hidden="true"
      shapeRendering="crispEdges"
    >
      {pixels.map((pixel) => (
        <rect
          key={pixel.id}
          x={pixel.x}
          y={pixel.y}
          width="1"
          height="1"
          fill={palette[pixel.color]}
        />
      ))}
    </svg>
  );
}
